AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: User-Service-Deployment-Descriptor

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: java11
    MemorySize: 1024
    Timeout: 20
    AutoPublishAlias: !Ref Stage
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    CodeUri: ./application
    Tags:
      Stage: !Ref Stage
      Service: LmsUser
      Resource: Lambda
    Environment:
      Variables:
        TABLE: !Ref LmsUserTable
        APPLICATION_ENVIRONMENT: !Ref Stage
        CLOUD_REGION: us-east-1
        MAIN_CLASS: com.tekcapzule.lms.user.application.UserApplication
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:

  # Setup API Gateway

  LmsUserApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "user-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For, Content-Type, Authorization, X-User-Login, X-Channel-Code'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false
      Variables:
        LAMBDA_ALIAS: !Ref Stage

  # Setup DynamoDB Table

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}LmsUser"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Setup Lambda Functions

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-CreateUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/create
            Method: post
            RestApiId:
              Ref: LmsUserApi

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-UpdateUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: updateFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/update
            Method: post
            RestApiId:
              Ref: LmsUserApi

  DisableUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-DisableUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: disableFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/disable
            Method: post
            RestApiId:
              Ref: LmsUserApi
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-GetUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/get
            Method: post
            RestApiId:
              Ref: LmsUserApi

  FollowUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-FollowUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: followFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/follow
            Method: post
            RestApiId:
              Ref: LmsUserApi

  UnfollowUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-UnfollowUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: unfollowFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/unfollow
            Method: post
            RestApiId:
              Ref: LmsUserApi
  AddBookmarkUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-RegisterCourseUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: registerCourse
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/bookmark
            Method: post
            RestApiId:
              Ref: LmsUserApi

  RemoveBookmarkUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-DeregisterCourseUser"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: deregisterCourseFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/deregisterCourse
            Method: post
            RestApiId:
              Ref: LmsUserApi

  GetUsersCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Lms-User-GetUsersCount"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LmsUserTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getCountFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: lms/user/getCount
            Method: post
            RestApiId:
              Ref: LmsUserApi


  # Set Output Variable

Outputs:
  ApiEndpoint:
    Description: "LMS User API endpoint."
    Value: !Sub "https://${LmsUserApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/lms/user"